#!/bin/sh

echo $path
nodejs --version
cd /home/jdorlus/Sites/Node/TPCv4
npm --version
git pull origin master
npm test
npm install --production
chmod 777 ../TPCv4
chmod 777 ../TPCv4/**/*
chmod 777 ../TPCv4/**/**
forever restartall
exit
EOF