#!/bin/sh

nodejs --version
npm --version
npm install -g bower
npm install -g grunt-cli
reinstall
bower install
grunt build
npm rebuild node-sass
forever start app.js
cd ~/Sites/Node/ghost
NODE_ENV=production forever start index.js
forever restartall
exit
EOF