language: node_js
node_js:
- 0.12.7
#before_install:
#- npm install -g bower
#- npm install -g grunt-cli
#- gem install sass -v 3.4.13
#- gem install compass -v 1.0.3
#before_script:
deploy:
  provider: heroku
  app: thepowercoder
  api_key:
    secure: I6uQcMoXkIzkwIXmN9j6w4xaFJykRHJm0fUSAS1Ncf5KfsZiRM6kaaKvo15RAbO70lJ9xp5mTK1L2dMY1MGj8Fq+049tZCVOqBfYm8EEo0KTsOK0mMbSQ2JiPIxG2fC94Kx/cWbr6cC99Gg7Nx5s9D71nefWOmBghoA2mDCExW0=
  skip_cleanup: true