language: node_js
node_js:
- 0.12.7
before_install:
- npm install -g bower
- bower install
- npm install -g grunt-cli
deploy:
  provider: heroku
  app: thepowercoder
  env:
    global:
      secure: VeD/IgmGhTQfHX96g0klVWMATYjX2W902t7zWvJmUSNofqZpH/wGPFHBNeH1/fCueN5y2cuo2AdNYniems+LkN1x4eJMrrUiCbaq4i46xGXJhF2jl23Rbqc9LB3o6vX6S1RC4KNtKyZoNjGdAPRMS3olDOSQbGjqWMgomtZiUic=
